<a href="https://colab.research.google.com/github/Sultoniromadhon/data-science-2026/blob/main/Pertemuan2_Sultoni_Romadhon_250401020198.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* Nama : SULTONI ROMADHON
* NIM : 250401020198
* Kelas : IF403
* Prodi : Informatika PJJ S1

In [ ]:
mahasiswa = {
 'nama': 'Budi Santoso',
 'nim': '2024001',
 'prodi': 'Informatika',
 'ipk': 3.85
}
# Akses nilai
print(mahasiswa['nama']) # → 'Budi Santoso'
print(mahasiswa.get('usia', 0)) # default jika key tak ada
# Update dan hapus
mahasiswa['angkatan'] = 2024 # tambah key baru
del mahasiswa['nim'] # hapus key

Budi Santoso
0


In [ ]:
# Dari list Python
a1D = np.array([1, 2, 3, 4, 5]) # 1D
a2D = np.array([[1,2,3],[4,5,6]]) # 2D
# Array dengan nilai inisial
zeros = np.zeros((3, 4)) # nol semua
ones = np.ones((2, 3)) # satu semua
eye = np.eye(4) # matriks identitas
full = np.full((2, 2), 7) # nilai konstan
# Sequence
arange = np.arange(0, 20, 2) # 0,2,4,...18
linsp = np.linspace(0, 1, 11) # 11 titik merata
# Array acak (reproducible)
rng = np.random.default_rng(seed=42)
rand_int = rng.integers(0, 100, (3, 4))
rand_flt = rng.normal(loc=0, scale=1, size=(100,))

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
# Operasi aritmetika vektorisasi
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a + b) # → [11 22 33 44 55]
print(a * b) # → [10 40 90 160 250]
print(a ** 2) # → [1 4 9 16 25]
# Universal functions (ufuncs)
np.sqrt(a) # akar kuadrat tiap elemen
np.exp(a) # eksponensial (e^x)
np.log(b) # logaritma natural
# Fungsi statistik
data = rng.normal(0, 1, 1000)
print(f'Mean: {np.mean(data):.4f}')
print(f'Std: {np.std(data):.4f}')
print(f'Min: {np.min(data):.4f}')
print(f'Max: {np.max(data):.4f}')
print(f'Q1: {np.percentile(data,25):.4f}')
print(f'Q3: {np.percentile(data,75):.4f}')

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
Mean: -0.0163
Std: 1.0008
Min: -3.6484
Max: 3.1789
Q1: -0.6897
Q3: 0.6163


In [ ]:


# Series dari list — index default 0,1,2...
s1 = pd.Series([85, 92, 78, 95, 88])
# Series dengan index kustom
nilai = pd.Series(
 [85, 92, 78, 95],
 index=['Alice','Bob','Caca','Dina']
)
print(nilai['Bob']) # → 92
print(nilai[nilai>80]) # filter
print(nilai.mean()) # → 87.5
print(nilai.describe()) # statistik lengkap

92
Alice    85
Bob      92
Dina     95
dtype: int64
87.5
count     4.000000
mean     87.500000
std       7.593857
min      78.000000
25%      83.250000
50%      88.500000
75%      92.750000
max      95.000000
dtype: float64


In [ ]:

data = {
 'nama': ['Ali','Budi','Caca','Dina'],
 'usia': [22, 25, 21, 23],
 'kota': ['Jakarta','Bandung','Surabaya','Medan'],
 'ipk': [3.8, 3.5, 3.9, 3.7]
}
df = pd.DataFrame(data)
# Informasi dasar
print(df.shape) # → (4, 4)
print(df.dtypes) # tipe data per kolom
print(df.columns) # nama-nama kolom

(4, 4)
nama     object
usia      int64
kota     object
ipk     float64
dtype: object
Index(['nama', 'usia', 'kota', 'ipk'], dtype='object')


In [ ]:
import pandas as pd
import numpy as np


# Membuat list
data = [10, 20, 'Python', True, 3.14]

# Akses & slicing
print(data[0])     # 10
print(data[-1])    # 3.14
print(data[1:3])   # [20, 'Python']

# Manipulasi
data.append(99)
data.insert(1, 55)
data.remove(20)

print(data)






10
3.14
[20, 'Python']
[10, 55, 'Python', True, 3.14, 99]


In [ ]:
# Memuat dari file lokal
df = pd.read_csv('data/penjualan.csv')
# Memuat dari URL (dataset publik)
url = "https://raw.githubusercontent.com/..."
df = pd.read_csv(url)

# Parameter penting
df = pd.read_csv('data.csv',
 sep=';', # pemisah kolom (default ',')
 encoding='utf-8', # encoding file
 index_col='ID', # kolom sebagai index
 parse_dates=['tgl'],# parse kolom tanggal
 na_values=['N/A','none'] # nilai kosong
)
# Eksplorasi standar setelah load
df.head() # 5 baris pertama
df.info() # tipe data & missing
df.describe() # statistik deskriptif

In [ ]:


# Contoh: Dataset Titanic
df = pd.read_csv(titanic_url)
# Filter satu kondisi
penumpang_selamat = df[df['Survived'] == 1]
penumpang_wanita = df[df['Sex'] == 'female']
# Filter kondisi ganda (& = AND, | = OR)
wanita_kelas1 = df[(df['Sex']=='female') &
 (df['Pclass']==1)]
# Seleksi kolom tertentu
df[['Name','Age','Sex','Survived']]

Kesimpulan

Pada pertemuan ini saya belajar menggunakan List, Dictionary, NumPy, dan Pandas untuk mengolah data. Saya juga belajar membaca dataset, melihat informasi data, mencari missing values, melakukan filtering, serta analisis sederhana menggunakan dataset Titanic.

Temuan utama dari analisis Titanic adalah tingkat keselamatan penumpang sekitar 38%, wanita memiliki peluang selamat lebih tinggi dibanding pria, dan penumpang kelas 1 memiliki tingkat keselamatan tertinggi. Selain itu, terdapat banyak data yang hilang pada kolom Cabin dan sebagian pada kolom Age.

Keterbatasan analisis ini adalah data yang digunakan masih berupa data mentah dan belum dilakukan pembersihan atau visualisasi data. Saya juga ingin mempelajari lebih lanjut cara menangani missing values dan membuat visualisasi agar hasil analisis lebih mudah dipahami.