<a href="https://colab.research.google.com/github/Sultoniromadhon/data-science-2026/blob/main/Pertemuan2_Sultoni_Romadhon_250401020198.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# Membuat list
data = [10, 20, 'Python', True, 3.14]

# Akses & slicing
print(data[0])     # 10
print(data[-1])    # 3.14
print(data[1:3])   # [20, 'Python']

# Manipulasi
data.append(99)
data.insert(1, 55)
data.remove(20)

print(data)



10
3.14
[20, 'Python']
[10, 55, 'Python', True, 3.14, 99]


In [19]:
mahasiswa = {
 'nama': 'Budi Santoso',
 'nim': '2024001',
 'prodi': 'Informatika',
 'ipk': 3.85
}
# Akses nilai
print(mahasiswa['nama']) # → 'Budi Santoso'
print(mahasiswa.get('usia', 0)) # default jika key tak ada
# Update dan hapus
mahasiswa['angkatan'] = 2024 # tambah key baru
del mahasiswa['nim'] # hapus key

Budi Santoso
0


In [15]:
import numpy as np

# Dari list Python
a1D = np.array([1, 2, 3, 4, 5])              # 1D
a2D = np.array([[1, 2, 3], [4, 5, 6]])      # 2D

# Array dengan nilai inisial
zeros = np.zeros((3, 4))   # nol semua
ones = np.ones((2, 3))     # satu semua
eye = np.eye(4)            # matriks identitas
full = np.full((2, 2), 7)  # nilai konstan

# Sequence
arr_range = np.arange(0, 20, 2)      # 0,2,4,...18
linsp = np.linspace(0, 1, 11)        # 11 titik merata

# Array acak (reproducible)
rng = np.random.default_rng(seed=42)
rand_int = rng.integers(0, 100, (3, 4))
rand_flt = rng.normal(loc=0, scale=1, size=(100,))

# Contoh output
print(a1D)
print(a2D)
print(arr_range)
print(linsp)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [22]:
import numpy as np

# Random generator
rng = np.random.default_rng(seed=42)

# Operasi aritmetika vektorisasi
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a + b)   # [11 22 33 44 55]
print(a * b)   # [10 40 90 160 250]
print(a ** 2)  # [1 4 9 16 25]

# Universal functions (ufuncs)
print(np.sqrt(a))
print(np.exp(a))
print(np.log(b))

# Fungsi statistik
data = rng.normal(0, 1, 1000)

print(f'Mean: {np.mean(data):.4f}')
print(f'Std: {np.std(data):.4f}')
print(f'Min: {np.min(data):.4f}')
print(f'Max: {np.max(data):.4f}')
print(f'Q1: {np.percentile(data,25):.4f}')
print(f'Q3: {np.percentile(data,75):.4f}')

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
Mean: -0.0289
Std: 0.9887
Min: -3.6484
Max: 3.1789
Q1: -0.6963
Q3: 0.5899


In [23]:
import pandas as pd

# Series dari list — index default
s1 = pd.Series([85, 92, 78, 95, 88])

# Series dengan index kustom
nilai = pd.Series(
    [85, 92, 78, 95],
    index=['Alice', 'Bob', 'Caca', 'Dina']
)

print(nilai['Bob'])           # 92
print(nilai[nilai > 80])      # filter
print(nilai.mean())           # rata-rata
print(nilai.describe())       # statistik lengkap

92
Alice    85
Bob      92
Dina     95
dtype: int64
87.5
count     4.000000
mean     87.500000
std       7.593857
min      78.000000
25%      83.250000
50%      88.500000
75%      92.750000
max      95.000000
dtype: float64


In [24]:
import pandas as pd

data = {
    'nama': ['Ali','Budi','Caca','Dina'],
    'usia': [22, 25, 21, 23],
    'kota': ['Jakarta','Bandung','Surabaya','Medan'],
    'ipk': [3.8, 3.5, 3.9, 3.7]
}

df = pd.DataFrame(data)

# Informasi dasar
print(df.shape)     # (4, 4)
print(df.dtypes)    # tipe data per kolom
print(df.columns)   # nama kolom

(4, 4)
nama     object
usia      int64
kota     object
ipk     float64
dtype: object
Index(['nama', 'usia', 'kota', 'ipk'], dtype='object')


In [30]:
import pandas as pd;
df = pd.read_csv('sample_data/customers-100.csv');
df['Subscription Date'] = pd.to_datetime(df['Subscription Date']);
print(df.head());
print(df.shape);
print(df.info());
print(df.isnull().sum());
print(df['Country'].value_counts());
print(df['City'].value_counts().head(10));
print(df['Company'].value_counts().head(10));
df['Year'] = df['Subscription Date'].dt.year;
print(df['Year'].value_counts());
print(df.describe(include='all'))

   Index      Customer Id First Name Last Name  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1      2  1Ef7b82A4CAAD10    Preston    Lozano   
2      3  6F94879bDAfE5a6        Roy     Berry   
3      4  5Cef8BFA16c5e3c      Linda     Olsen   
4      5  053d585Ab6b3159     Joanna    Bender   

                           Company               City  \
0                  Rasmussen Group       East Leonard   
1                      Vega-Gentry  East Jimmychester   
2                    Murillo-Perry      Isabelborough   
3  Dominguez, Mcmillan and Donovan         Bensonview   
4         Martin, Lang and Andrade     West Priscilla   

                      Country                 Phone 1                Phone 2  \
0                       Chile            229.077.5154       397.884.0519x718   
1                    Djibouti              5153435776       686-620-1820x944   
2         Antigua and Barbuda         +1-539-402-0259    (496)978-3969x58947   
3          Dominican Republic  001-8

In [31]:
import pandas as pd

# Dataset Titanic (contoh URL publik)
titanic_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(titanic_url)

# Filter satu kondisi
penumpang_selamat = df[df['Survived'] == 1]
penumpang_wanita = df[df['Sex'] == 'female']

# Filter kondisi ganda (& = AND, | = OR)
wanita_kelas1 = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]

# Seleksi kolom tertentu
kolom_terpilih = df[['Name', 'Age', 'Sex', 'Survived']]

# Output
print(penumpang_selamat.head())
print(penumpang_wanita.head())
print(wanita_kelas1.head())
print(kolom_terpilih.head())

   PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C  
  

In [2]:
# Langkah 4: Impor library
import pandas as pd


# Langkah 5: Muat dataset Titanic
# Catatan: Gunakan link raw agar data terbaca sempurna oleh Pandas
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Cek 5 baris pertama untuk memastikan data berhasil dimuat
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [9]:
# Q1 Berapa jumlah baris dan kolom pada dataset Titanic? Kolom apa saja yang tersedia?
# Jawaban Q1
print(f"Jumlah baris: {df.shape[0]}")
print(f"Daftar kolom: {df.columns.tolist()}")

Jumlah baris: 891
Jumlah kolom: 12
Daftar kolom: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']


In [11]:
# Q2 Kolom mana saja yang memiliki missing values? Berapa jumlah dan proporsinya (%)
# Jawaban Q2
missing = df.isnull().sum()
persen = (missing / len(df)) * 100

print("Jumlah missing per kolom:")
print(missing)

print("\nPersentase missing (%):")
print(persen)

Jumlah missing per kolom:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Persentase missing (%):
PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64


In [12]:
# Q3 Berapa persen penumpang yang selamat (Survived=1)?
# Jawaban Q3
print(f"Persentase selamat: {df['Survived'].mean() * 100:.2f}%")

Persentase selamat: 38.38%


In [16]:
# Q4 Filter penumpang wanita dari kelas 1 (Pclass=1)
# Jawaban Q4
wanita_kelas1 = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]

print(f"Jumlah wanita kelas 1: {len(wanita_kelas1)}")
print(f"Rata-rata usia: {wanita_kelas1['Age'].mean():.2f}")

Jumlah wanita kelas 1: 94
Rata-rata usia: 34.61


In [17]:
# Q5 Tingkat keselamatan per kelas penumpang
# Jawaban Q5
survival_per_class = df.groupby('Pclass')['Survived'].mean()

print("Survival rate per kelas:")
print(survival_per_class)

print(f"Kelas dengan survival tertinggi: {survival_per_class.idxmax()}")

Survival rate per kelas:
Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64
Kelas dengan survival tertinggi: 1


In [18]:
# Q6 Analisis tambahan (berdasarkan gender)
# Jawaban Q6
survival_gender = df.groupby('Sex')['Survived'].mean()

print("Survival rate berdasarkan gender:")
print(survival_gender)

print("\nInterpretasi: Wanita memiliki peluang selamat lebih tinggi dibanding pria.")

Survival rate berdasarkan gender:
Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

Interpretasi: Wanita memiliki peluang selamat lebih tinggi dibanding pria.
